### ISSUE TITLE
TODO: Fix issue with `internal:` links.

### ISSUE THREAD

**Issue by BrianGilbert** [druxt/druxt-entity#51]
**Is your feature request related to a problem? Please describe.**
Intefrnal links need to be presented without `internal:` part of the value so that we don't need to remove this on usage.

**Describe the solution you'd like**
receive value without internal: text as part of it.

**Additional context**
Todo at; https://github.com/druxt/druxt-entity/blob/develop/src/components/fields/DruxtFieldLink.vue#L54

**Comment by Decipher** [comment]
There is ongoing work in Drupal that relates to this issue: https://www.drupal.org/project/drupal/issues/3066751

In the meantime we will have to strip out this value.
