### ISSUE TITLE
TODO: Move DruxtEntityContextMixin to a common module.

### ISSUE THREAD

**Issue by BrianGilbert** [druxt/druxt-entity#56]
**Is your feature request related to a problem? Please describe.**
This is reuable by other Druxt related nuxt.js modules, lets move it to somewhere they could access.

**Additional context**
Todo at: https://github.com/druxt/druxt-entity/blob/develop/src/components/fields/context.js#L34

**Comment by Decipher** [comment]
This mixin has been deprecated in favour of `DruxtModule`.
