### ISSUE TITLE
Display Paragraph field output

### ISSUE THREAD

**Issue by tanc** [druxt/druxt-entity#98]
**Is your feature request related to a problem? Please describe.**
Hi Stuart, I'm giving Druxt a test and one of my criteria when evaluating decoupled projects is the ability to handle Paragraphs and ideally Paragraphs Layouts. I'm just beginning to understand how Druxt fits together but there are still massive gaps in my understanding. Am I right in thinking to support/display Paragraphs there would need to be a Paragraph field component in Druxt?

At the moment when I output a field in a node entity component with `<slot name="field_content" />` I get the following markup:

```
<div data-fetch-key="DruxtField:1" class="field"><div items="[object Object],[object Object],[object Object],[object Object]" schema="[object Object]" data-fetch-key="DruxtField:1"></div></div>
```

The `field_content` field is a Paragraphs reference revisions field.

**Describe the solution you'd like**
I'd like a way of outputting potentially complex nested paragraphs.

**Describe alternatives you've considered**
I've tried to use `<DruxtEntity type="paragraph--columns" :uuid="uuid" />` but it results in:

```
Error in fetch(): Error: Cannot find module './paragraph--columns--default--view.json'
    at eval (eval at ./.nuxt/schemas lazy recursive ^\.\/.*\.json$ (app.js:394), <anonymous>:70:12)
```

I don't know enough about the system to understand what it is referring to here.

**Additional context**

Nothing for now but let me know what you need.

**Comment by tanc** [comment]
I did some more experimenting and it looks like Paragraphs _are_ supported. I introduced a simple paragraphs field called `field_test` and placed two paragraphs in it with some basic text content. I modified the node template in Vue at `components/druxt/entity/node/page/Default.vue` and add the slot of the new paragraphs field:
```
<slot name="field_test" />
```
I then restarted the dev server and reloaded the page and I could see both paragraphs have been output from that field.

To confirm its layout paragraphs that aren't supported I went back to Drupal and changed the field format for the `field_content` from "Layout Paragraphs" back to "Rendered Entity" and confirmed this allowed the `field_content` to display properly in the Vue app.
 
So I guess this is a feature request to support layout paragraphs as they appear to work a bit differently.

My goal is for editors to place paragraphs in layout paragraphs regions and have that come through to the front end in some way that can be interpreted into a layout.

**Comment by tanc** [comment]
A little further forward now. I discovered the field naming convention I needed to use by looking at the component in $children and its `component.options` property. I created `DruxtFieldLayoutParagraphsFieldContent.vue` and added this:

```
<template>
  <component :is="wrapper.component" v-bind="wrapper.props">
    <!-- Label: Above -->
    <div v-if="$slots['label-above']">
      <slot name="label-above" />
    </div>

    <!-- Label: Inline -->
    <slot v-if="$slots['label-inline']" name="label-inline" />

    <DruxtEntity
      v-for="item of items"
      :key="item.uuid"
      v-bind="{ ...item, ...props }"
    />
  </component>
</template>

<script>
import { DruxtFieldEntityReferenceEntityView } from 'druxt-entity'

export default {
  name: 'DruxtFieldLayoutParagraphsFieldContent',
  extends: DruxtFieldEntityReferenceEntityView,
}
</script>
```

Now the field is outputting correctly, in that it outputs the same as the usual paragraphs field format (rendered entity). I'm also seeing that same schema error as before though:

```
Error in fetch(): Error: Cannot find module './paragraph--columns--default--view.json'
    at server.js:1911:12
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'MODULE_NOT_FOUND'
}
```

**Comment by tanc** [comment]
I'm now thinking that the issue is more with how the layout paragraphs and I suspect any nested paragraph is represented in JSON API.

At least I can potentially create my own hierarchy from the field contents as the JSON API provides enough to work out a relationship:

<details>
<summary>Example JSON for the `field_content` paragraph field</summary>

```javascript
{
  "jsonapi": {
    "version": "1.0",
    "meta": {
      "links": {
        "self": {
          "href": "http://jsonapi.org/format/1.0/"
        }
      }
    }
  },
  "data": [
    {
      "type": "paragraph--columns",
      "id": "07a0fe1a-f244-4ac9-9056-ad3b8b0baf4a",
      "links": {
        "self": {
          "href": "http://druxt.lndo.site/jsonapi/paragraph/columns/07a0fe1a-f244-4ac9-9056-ad3b8b0baf4a"
        }
      },
      "attributes": {
        "drupal_internal__id": 7,
        "drupal_internal__revision_id": 28,
        "langcode": "en",
        "status": true,
        "created": "2021-04-17T11:02:29+00:00",
        "parent_id": "1",
        "parent_type": "node",
        "parent_field_name": "field_content",
        "behavior_settings": {
          "layout_paragraphs": {
            "region": "",
            "parent_uuid": "",
            "layout": "druxt_layouts_column_two",
            "config": {
              "label": ""
            }
          }
        },
        "default_langcode": true,
        "revision_translation_affected": null
      },
      "relationships": {
        "paragraph_type": {
          "data": {
            "type": "paragraphs_type--paragraphs_type",
            "id": "c7096092-517d-468f-8642-7a4e4d9a8665"
          },
          "links": {
            "related": {
              "href": "http://druxt.lndo.site/jsonapi/paragraph/columns/07a0fe1a-f244-4ac9-9056-ad3b8b0baf4a/paragraph_type"
            },
            "self": {
              "href": "http://druxt.lndo.site/jsonapi/paragraph/columns/07a0fe1a-f244-4ac9-9056-ad3b8b0baf4a/relationships/paragraph_type"
            }
          }
        }
      }
    },
    {
      "type": "paragraph--text",
      "id": "ff9992c4-8e51-4b05-97aa-4f7068fb0059",
      "links": {
        "self": {
          "href": "http://druxt.lndo.site/jsonapi/paragraph/text/ff9992c4-8e51-4b05-97aa-4f7068fb0059"
        }
      },
      "attributes": {
        "drupal_internal__id": 8,
        "drupal_internal__revision_id": 29,
        "langcode": "en",
        "status": true,
        "created": "2021-04-17T11:02:35+00:00",
        "parent_id": "1",
        "parent_type": "node",
        "parent_field_name": "field_content",
        "behavior_settings": {
          "layout_paragraphs": {
            "region": "content_first",
            "parent_uuid": "07a0fe1a-f244-4ac9-9056-ad3b8b0baf4a",
            "layout": "",
            "config": [],
            "parent_delta": 0
          }
        },
        "default_langcode": true,
        "revision_translation_affected": null,
        "field_content_text": {
          "value": "<p>Some text in the first column</p>\r\n",
          "format": "basic_html",
          "processed": "<p>Some text in the first column</p>"
        }
      },
      "relationships": {
        "paragraph_type": {
          "data": {
            "type": "paragraphs_type--paragraphs_type",
            "id": "edd2aa78-954f-402f-a197-4246b9b9dcb4"
          },
          "links": {
            "related": {
              "href": "http://druxt.lndo.site/jsonapi/paragraph/text/ff9992c4-8e51-4b05-97aa-4f7068fb0059/paragraph_type"
            },
            "self": {
              "href": "http://druxt.lndo.site/jsonapi/paragraph/text/ff9992c4-8e51-4b05-97aa-4f7068fb0059/relationships/paragraph_type"
            }
          }
        }
      }
    },
    {
      "type": "paragraph--text",
      "id": "b364b88d-6f23-45b8-acea-19a0bd0e24e3",
      "links": {
        "self": {
          "href": "http://druxt.lndo.site/jsonapi/paragraph/text/b364b88d-6f23-45b8-acea-19a0bd0e24e3"
        }
      },
      "attributes": {
        "drupal_internal__id": 9,
        "drupal_internal__revision_id": 30,
        "langcode": "en",
        "status": true,
        "created": "2021-04-17T11:02:46+00:00",
        "parent_id": "1",
        "parent_type": "node",
        "parent_field_name": "field_content",
        "behavior_settings": {
          "layout_paragraphs": {
            "region": "content_second",
            "parent_uuid": "07a0fe1a-f244-4ac9-9056-ad3b8b0baf4a",
            "layout": "",
            "config": [],
            "parent_delta": 0
          }
        },
        "default_langcode": true,
        "revision_translation_affected": null,
        "field_content_text": {
          "value": "<p>Some text in the second column</p>\r\n",
          "format": "basic_html",
          "processed": "<p>Some text in the second column</p>"
        }
      },
      "relationships": {
        "paragraph_type": {
          "data": {
            "type": "paragraphs_type--paragraphs_type",
            "id": "edd2aa78-954f-402f-a197-4246b9b9dcb4"
          },
          "links": {
            "related": {
              "href": "http://druxt.lndo.site/jsonapi/paragraph/text/b364b88d-6f23-45b8-acea-19a0bd0e24e3/paragraph_type"
            },
            "self": {
              "href": "http://druxt.lndo.site/jsonapi/paragraph/text/b364b88d-6f23-45b8-acea-19a0bd0e24e3/relationships/paragraph_type"
            }
          }
        }
      }
    }
  ],
  "links": {
    "self": {
      "href": "http://druxt.lndo.site/jsonapi/node/page/70987fbb-63a5-4860-b675-63481d0d315b/field_content?resourceVersion=id%3A11"
    }
  }
}
```

</details>

**Comment by Decipher** [comment]
Good morning @tanc,

Just a quick answer based over the initial error, before I follow up more thoroughly.

The Schema module can only build the required file if Drupal has exposed the data, and it doesn't expose all display data by default.

The quick fix is to go to the Manage Display of that Entity/Bundle, and hit the save button.

**Comment by Decipher** [comment]
> Am I right in thinking to support/display Paragraphs there would need to be a Paragraph field component in Druxt?

> I did some more experimenting and it looks like Paragraphs are supported.

> I discovered the field naming convention I needed to use by looking at the component in $children and its `component.options` property.

As you discovered yourself, Paragraphs is supported, and any field that isn't can be added using a correctly named component.

> To confirm its layout paragraphs that aren't supported...

I haven't used the [Layout Paragraphs](https://www.drupal.org/project/layout_paragraphs) module yet, but adding the custom component is the correct approach.

> I'm also seeing that same schema error as before though

There's an open issue in the Schema module for this, but the above workaround should resolve the issue for the moment.

https://github.com/druxt/druxt-schema/issues/44

**Comment by tanc** [comment]
| The quick fix is to go to the Manage Display of that Entity/Bundle, and hit the save button.

Confirmed! Thanks for the fix.

I think I'm now at the point where Druxt is working as it should and the issue is more with the structure that JSON API presents for nested Paragraphs so I'll continue my exploration in that area. I may well come up with a Druxt/Vue component that does a bit of processing to render the sub paragraphs in the correct 'regions' in the front end.

I'll close this issue as the original question has been answered. If I come up with a re-usable solution I'll drop something in here.
